general.import = [
"~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 11.5

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Right", mods = "Shift", action = "Copy" },
  { mouse = "Right", action = "Paste" },
]

[env]
TERM = "xterm-256color"
